version: "23.1016.0"

title: "An awesome blog"
baseurl: ""
permalink: "/:title"
locale: "zh_CN"
timezone: "Asia/Shanghai"

author: "sendevia"
mugshot: "/assets/images/avatar.webp"
email: ""
github: ""

impression: "/assets/images/102911375_p0.webp"

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "Page"
      permalink: "/:basename"
  - scope:
      path: "_posts"
    values:
      layout: "Post"
      permalink: "/posts/:title"
      toc: true

toc:
  item_class: "JTM-C-NavigationDrawer-Entry"
  item_prefix: "JTM-C-NavigationDrawer-"
  list_id: "JTM-C-NavigationDrawer-Section"
  max_level: 2
  ordered_list: false

markdown: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "rouge"
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

webrick:
  headers:
    Cache-Control: "must-revalidate"

exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - node_modules/
  - package-lock.json
  - package.json
  - README.MD
  - sendevia.page.jekyll.code-workspace
  - tsconfig.json
  - vendor/
  - webpack.config.js
  - babel.config.js
  - webpack/

include:
  - _pages/
