baseurl: ""
timezone: Asia/Shanghai
title: "An awesome blog"

email: "me@sendevia.top"
github: "https://github.com/Sendevia"
twitter: "https://twitter.com/sendevia"

header_image: "/assets/images/102911375_p0.webp"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jemoji

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "Material3"
      toc: true

toc:
  item_class: mnd-entry
  item_prefix: mnd-
  list_class: mnd-section
  list_id:
  max_level: 2
  ordered_list: false

highlighter: "rouge"
markdown: "kramdown"
kramdown:
  input: "GFM"
  syntax_highlighter: "rouge"

webrick:
  headers:
    Cache-Control: "must-revalidate"

exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - .typescript
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - node_modules/
  - package-lock.json
  - package.json
  - README.MD
  - sendevia.page.jekyll.code-workspace
  - tsconfig.json
  - vendor/
  - webpack.config.js
  - webpack/
